# -*- coding: utf-8 -*-
"""spur-gear-calc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FP49Hnx7nz-xxN_J7tzqFCyEEDXDUjuv
"""

#given, tooth number(N) and diametral pitch(P)
#deduce pitch diameter(d), circular pitch(p), addendum(a), dedendum(b), tooth thickness(s), clearance
#pi = 3.1416
import math

#Pitch diameter (d): Diameter of the pitch circle.
#d = N/P
def pitch_diameter(N, P):
  return N/P

#Circular pitch (p): Measurement of the pitch circle arc length from one point on a tooth to the same point on the adjacent tooth.
#p = pi/P
def circular_pitch(N, P):
  return math.pi/P

#tool thickness(s): addendum + dedendum
#s = p/2
def tool_thickness(N, P):
  return circular_pitch(N, P)/2

#addendum(a): 4/9 times tool thickness
#a = (4*s)/9
def addendum(N, P):
  return (4*tool_thickness(N, P))/9

#dedendum(b) =
#b = (5*s)/9
def dedendum(N, P):
  return (5*tool_thickness(N, P))/9

#clearance(c): dedendum - addendum
#c = b - a
def clearance(N, P):
  return dedendum(N, P) - addendum(N, P)